# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

variables:
  # Conexi贸n del servicio de registro de contenedores establecida durante la creaci贸n de la canalizaci贸n
  #dockerRegistryServiceConnection: '{{ containerRegistryConnection.Id }}'
  dockerRegistryServiceConnection: serviceDockerHub
  #imageRepository: '{{#toAlphaNumericString imageRepository 50}}{{/toAlphaNumericString}}'
  imagenRepository: 'ws-project'
  #containerRegistry: '{{ containerRegistryConnection.Authorization.Parameters.loginServer }}'
  containerRegistry: serviceDockerHub
  #dockerfilePath: '{{ dockerfilePath }}'
  dockerfilePath: '**/Dockerfile'
  #tag: '$(Build.BuildId)'
  #tag: 

jobs:

- job: CreateImageCompilePom
  displayName: Comienzo de la compilaci贸n

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Maven@3
    displayName: 'Compilacion con Maven al pom'
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      #testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
  - script: |
      echo Finalizo la compilacion de Maven.
  - task: Docker@2
    displayName: 'Logueado a Container Registry Docker'
    inputs:
      command: login
      containerRegistry: serviceDockerHub
  - script: |
      echo Se logueo correctamente
  - task: Docker@2
    displayName: 'Compilar el DockerFile y empuja a Docker Hub'
    inputs:
      command: buildAndPush
      dockerfile: $(dockerfilePath)
      arguments:  --build-arg artifact_id=ws-project --build-arg artifact_version=1.1 -t ws-project:1.1
  - script: |
      echo Finalizo el empuje a Docker Hub